name: Python Tests

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    
    - name: Run tests for desafio1
      run: |
        cd desafio1
        python -m unittest discover -p "teste*.py"
        
    - name: Run tests for desafio3
      run: |
        cd desafio3
        python -m unittest discover -p "teste*.py"
